language: python
python:
  - "2.6"
  - "2.7"

install:
  - easy_install -i http://tg.gy/215 tg.devtools
  - python setup.py develop

script: python setup.py nosetest

before_install:
  - sudo apt-get -qq update && sudo apt-get -qq install gcc default-jdk
