language: python

python:
- 2.6
- 2.7
env:
- TG2_VERSION=2.1.5
- TG2_VERSION=2.2.0
- TG2_VERSION=2.2.1
- TG2_VERSION=2.2.2
- TG2_VERSION=current
- TG2_VERSION=""
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - travis

cache:
  apt: true
  directories:
  - $HOME/.pip-cache

before_install:
- git submodule update --init --recursive
- sudo apt-get update -qq
install:
- sudo apt-get install -qq openjdk-7-jdk gcc g++
- sudo apt-get install -qq gfortran libfreetype6-dev
- travis_retry pip install --download-cache=$HOME/.pip-cache -i http://tg.gy/${TG2_VERSION//./}/ tg.devtools
- travis_retry pip install --download-cache=$HOME/.pip-cache -M -e .[similarity,lti,nosetests]
- travis_retry pip install --download-cache=$HOME/.pip-cache -M python-coveralls
before_script:
- pip freeze
script:
- python setup.py nosetests
after_success:
- coveralls

notifications:
  email:
    recipients:
    - moschlar@metalabs.de
    on_success: change
    on_failure: always

deploy:
  - provider: heroku
    api_key:
      secure: YKP5iWrB+xiYFHSjg76n7FmE2osK5JK4/mOXoBDH0+iKe8nNttbgP1YrEvwpbdrAy7PFL/ADkOdcp/zaoudB1ODFc1iEml4uraEy74RTKYlcZmaXNfwFty6ctJR+RNqFHvOC4Ez1sF1+Cg/aoNcYliNtFOXGsmax2osubZgurUI=
    app: sauce-moschlar
    on:
      repo: moschlar/SAUCE
      branch: develop
      python: 2.7
      condition: "$TG2_VERSION = current"

  - provider: openshift
    user: mail@moritz-schlarb.de
    password:
      secure: he9mRCYikWNz799INO7Y42qSjgrO7cjP6sHy8zxAB0cRhHNDwWOIJ/b3NpwUJeJHOJUU8s+z0W1jU2OpsiWDvpbwUFsH1c/EDx3U0cjMX4x0jV/oAfCpCgQ0V0OH6Rmg5MVZtGbbz9NnZpDW8tD8KYl54LeFnLTEndLxM9+Ecls=
    app: sauce
    domain: moschlar
    on:
      repo: moschlar/SAUCE
      branch: develop
      python: 2.7
      condition: "$TG2_VERSION = current"
