language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update -qq
# We don't need all the build dependencies for numpy and matplotlib
# so we just explicitly install only gfortran and libfreetype6-dev
#  - apt-get build-dep -qq python-numpy python-matplotlib
  - sudo apt-get install -qq gfortran libfreetype6-dev
  - sudo apt-get install -qq openjdk-7-jdk gcc g++

install:
# We install the most awful dependencies separately to avoid confusion
  - easy_install -q numpy
  - easy_install -q matplotlib
  - easy_install -q -i http://tg.gy/215 tg.devtools
  - python setup.py -q develop

script:
  - python setup.py nosetests

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/

notifications:
  email:
    recipients:
      - sauce@moritz-schlarb.de
    on_success: change
    on_failure: always
