language: python
python:
  - "2.6"
  - "2.7"

install:
  - easy_install -q -i http://tg.gy/215 tg.devtools nose coverage
  - python setup.py develop -q

script: python setup.py nosetests

before_install:
  - sudo apt-get -qq update && sudo apt-get -qq install gcc openjdk-6-jdk

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - sauce@moritz-schlarb.de
    on_success: change
    on_failure: always
