language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get -qq update && sudo apt-get -qq install openjdk-7-jdk gcc gfortran

install:
  - easy_install -q numpy
  - easy_install -q -i http://tg.gy/215 tg.devtools
  - python setup.py develop -q

script: python setup.py nosetests

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/

notifications:
  email:
    recipients:
      - sauce@moritz-schlarb.de
    on_success: change
    on_failure: always
