language: python
python:
  - "2.6"
  - "2.7"

install:
  - easy_install -i http://tg.gy/215 tg.devtools
  - python setup.py install

script: python setup.py test

before_install:
  - sudo apt-get update
  - sudo apt-get install gcc default-jdk
